version: "2"

services:
  demo:
   image: magnustiberius/demo:0.0.2-SNAPSHOT
   ports:
     - "8090:8080"
   networks:
     demonet:
       ipv4_address: 172.19.0.3

  dyndb:
    image: dwmkerr/dynamodb
    ports:
      - "4001:8000"
    networks:
      demonet:
        ipv4_address: 172.19.0.2


networks:
  demonet:
   driver: bridge
   ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1
