version: "2"

services:
  demo:
   image: magnustiberius/demo:0.0.1-SNAPSHOT 
   ports:
     - "8080:8080"
   networks:
     mtrnet:
       ipv4_address: 172.18.0.3

  dyndb:
    image: dwmkerr/dynamodb
    ports:
      - "3001:8000"
    networks:
      mtrnet:
        ipv4_address: 172.18.0.2


networks:
  mtrnet:
   driver: bridge
   ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1
